//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\Project\hz\WindowsFormsApplication2\WindowsFormsApplication2\PreSQL.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace PreSQL {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PreSQLParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public interface IPreSQLListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_name([NotNull] PreSQLParser.Type_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_name([NotNull] PreSQLParser.Type_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.drop_index_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrop_index_stmt([NotNull] PreSQLParser.Drop_index_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.drop_index_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrop_index_stmt([NotNull] PreSQLParser.Drop_index_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_name([NotNull] PreSQLParser.Table_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_name([NotNull] PreSQLParser.Table_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.join_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoin_constraint([NotNull] PreSQLParser.Join_constraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.join_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoin_constraint([NotNull] PreSQLParser.Join_constraintContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.cte_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCte_table_name([NotNull] PreSQLParser.Cte_table_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.cte_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCte_table_name([NotNull] PreSQLParser.Cte_table_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.indexed_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexed_column([NotNull] PreSQLParser.Indexed_columnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.indexed_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexed_column([NotNull] PreSQLParser.Indexed_columnContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.literal_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral_value([NotNull] PreSQLParser.Literal_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.literal_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral_value([NotNull] PreSQLParser.Literal_valueContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.disconnect_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisconnect_stmt([NotNull] PreSQLParser.Disconnect_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.disconnect_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisconnect_stmt([NotNull] PreSQLParser.Disconnect_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.transaction_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTransaction_name([NotNull] PreSQLParser.Transaction_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.transaction_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTransaction_name([NotNull] PreSQLParser.Transaction_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.column_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_def([NotNull] PreSQLParser.Column_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.column_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_def([NotNull] PreSQLParser.Column_defContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.sql_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSql_stmt([NotNull] PreSQLParser.Sql_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.sql_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSql_stmt([NotNull] PreSQLParser.Sql_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.new_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNew_table_name([NotNull] PreSQLParser.New_table_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.new_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNew_table_name([NotNull] PreSQLParser.New_table_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword([NotNull] PreSQLParser.KeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword([NotNull] PreSQLParser.KeywordContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.error_message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterError_message([NotNull] PreSQLParser.Error_messageContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.error_message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitError_message([NotNull] PreSQLParser.Error_messageContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.create_index_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreate_index_stmt([NotNull] PreSQLParser.Create_index_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.create_index_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreate_index_stmt([NotNull] PreSQLParser.Create_index_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_operator([NotNull] PreSQLParser.Unary_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_operator([NotNull] PreSQLParser.Unary_operatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.rollback_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRollback_stmt([NotNull] PreSQLParser.Rollback_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.rollback_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRollback_stmt([NotNull] PreSQLParser.Rollback_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.join_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoin_operator([NotNull] PreSQLParser.Join_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.join_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoin_operator([NotNull] PreSQLParser.Join_operatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.collation_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCollation_name([NotNull] PreSQLParser.Collation_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.collation_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCollation_name([NotNull] PreSQLParser.Collation_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.update_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUpdate_stmt([NotNull] PreSQLParser.Update_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.update_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUpdate_stmt([NotNull] PreSQLParser.Update_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.column_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_alias([NotNull] PreSQLParser.Column_aliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.column_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_alias([NotNull] PreSQLParser.Column_aliasContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.alter_table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlter_table_stmt([NotNull] PreSQLParser.Alter_table_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.alter_table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlter_table_stmt([NotNull] PreSQLParser.Alter_table_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] PreSQLParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] PreSQLParser.NameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.table_or_index_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_or_index_name([NotNull] PreSQLParser.Table_or_index_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.table_or_index_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_or_index_name([NotNull] PreSQLParser.Table_or_index_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.module_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule_name([NotNull] PreSQLParser.Module_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.module_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule_name([NotNull] PreSQLParser.Module_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.table_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_alias([NotNull] PreSQLParser.Table_aliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.table_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_alias([NotNull] PreSQLParser.Table_aliasContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.drop_trigger_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrop_trigger_stmt([NotNull] PreSQLParser.Drop_trigger_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.drop_trigger_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrop_trigger_stmt([NotNull] PreSQLParser.Drop_trigger_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.module_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule_argument([NotNull] PreSQLParser.Module_argumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.module_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule_argument([NotNull] PreSQLParser.Module_argumentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.create_trigger_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreate_trigger_stmt([NotNull] PreSQLParser.Create_trigger_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.create_trigger_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreate_trigger_stmt([NotNull] PreSQLParser.Create_trigger_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.signed_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSigned_number([NotNull] PreSQLParser.Signed_numberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.signed_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSigned_number([NotNull] PreSQLParser.Signed_numberContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.ordering_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrdering_term([NotNull] PreSQLParser.Ordering_termContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.ordering_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrdering_term([NotNull] PreSQLParser.Ordering_termContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.table_or_subquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_or_subquery([NotNull] PreSQLParser.Table_or_subqueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.table_or_subquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_or_subquery([NotNull] PreSQLParser.Table_or_subqueryContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.error"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterError([NotNull] PreSQLParser.ErrorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.error"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitError([NotNull] PreSQLParser.ErrorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.commit_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommit_stmt([NotNull] PreSQLParser.Commit_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.commit_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommit_stmt([NotNull] PreSQLParser.Commit_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.select_or_values"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelect_or_values([NotNull] PreSQLParser.Select_or_valuesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.select_or_values"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelect_or_values([NotNull] PreSQLParser.Select_or_valuesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.select_core"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelect_core([NotNull] PreSQLParser.Select_coreContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.select_core"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelect_core([NotNull] PreSQLParser.Select_coreContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.savepoint_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSavepoint_name([NotNull] PreSQLParser.Savepoint_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.savepoint_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSavepoint_name([NotNull] PreSQLParser.Savepoint_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.conflict_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConflict_clause([NotNull] PreSQLParser.Conflict_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.conflict_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConflict_clause([NotNull] PreSQLParser.Conflict_clauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.trigger_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrigger_name([NotNull] PreSQLParser.Trigger_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.trigger_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrigger_name([NotNull] PreSQLParser.Trigger_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.foreign_key_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeign_key_clause([NotNull] PreSQLParser.Foreign_key_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.foreign_key_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeign_key_clause([NotNull] PreSQLParser.Foreign_key_clauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.any_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAny_name([NotNull] PreSQLParser.Any_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.any_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAny_name([NotNull] PreSQLParser.Any_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.insert_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInsert_stmt([NotNull] PreSQLParser.Insert_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.insert_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInsert_stmt([NotNull] PreSQLParser.Insert_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.common_table_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommon_table_expression([NotNull] PreSQLParser.Common_table_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.common_table_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommon_table_expression([NotNull] PreSQLParser.Common_table_expressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.drop_table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrop_table_stmt([NotNull] PreSQLParser.Drop_table_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.drop_table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrop_table_stmt([NotNull] PreSQLParser.Drop_table_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] PreSQLParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] PreSQLParser.ExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.create_table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreate_table_stmt([NotNull] PreSQLParser.Create_table_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.create_table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreate_table_stmt([NotNull] PreSQLParser.Create_table_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.drop_view_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrop_view_stmt([NotNull] PreSQLParser.Drop_view_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.drop_view_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrop_view_stmt([NotNull] PreSQLParser.Drop_view_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.index_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndex_name([NotNull] PreSQLParser.Index_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.index_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndex_name([NotNull] PreSQLParser.Index_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.view_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterView_name([NotNull] PreSQLParser.View_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.view_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitView_name([NotNull] PreSQLParser.View_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.with_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWith_clause([NotNull] PreSQLParser.With_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.with_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWith_clause([NotNull] PreSQLParser.With_clauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.qualified_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualified_table_name([NotNull] PreSQLParser.Qualified_table_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.qualified_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualified_table_name([NotNull] PreSQLParser.Qualified_table_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.create_view_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreate_view_stmt([NotNull] PreSQLParser.Create_view_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.create_view_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreate_view_stmt([NotNull] PreSQLParser.Create_view_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.column_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_constraint([NotNull] PreSQLParser.Column_constraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.column_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_constraint([NotNull] PreSQLParser.Column_constraintContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.database_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatabase_name([NotNull] PreSQLParser.Database_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.database_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatabase_name([NotNull] PreSQLParser.Database_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.connect_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConnect_stmt([NotNull] PreSQLParser.Connect_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.connect_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConnect_stmt([NotNull] PreSQLParser.Connect_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_name([NotNull] PreSQLParser.Column_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_name([NotNull] PreSQLParser.Column_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.result_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResult_column([NotNull] PreSQLParser.Result_columnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.result_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResult_column([NotNull] PreSQLParser.Result_columnContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParse([NotNull] PreSQLParser.ParseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParse([NotNull] PreSQLParser.ParseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.table_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_constraint([NotNull] PreSQLParser.Table_constraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.table_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_constraint([NotNull] PreSQLParser.Table_constraintContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.pragma_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPragma_name([NotNull] PreSQLParser.Pragma_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.pragma_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPragma_name([NotNull] PreSQLParser.Pragma_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.foreign_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeign_table([NotNull] PreSQLParser.Foreign_tableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.foreign_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeign_table([NotNull] PreSQLParser.Foreign_tableContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_name([NotNull] PreSQLParser.Function_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_name([NotNull] PreSQLParser.Function_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.join_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoin_clause([NotNull] PreSQLParser.Join_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.join_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoin_clause([NotNull] PreSQLParser.Join_clauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.raise_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaise_function([NotNull] PreSQLParser.Raise_functionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.raise_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaise_function([NotNull] PreSQLParser.Raise_functionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.select_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelect_stmt([NotNull] PreSQLParser.Select_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.select_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelect_stmt([NotNull] PreSQLParser.Select_stmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PreSQLParser.delete_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDelete_stmt([NotNull] PreSQLParser.Delete_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreSQLParser.delete_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDelete_stmt([NotNull] PreSQLParser.Delete_stmtContext context);
}
} // namespace WindowsFormsApplication2
