//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\Project\hz\WindowsFormsApplication2\WindowsFormsApplication2\PreSQL.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace PreSQL {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PreSQLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public interface IPreSQLVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_name([NotNull] PreSQLParser.Type_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.drop_index_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_index_stmt([NotNull] PreSQLParser.Drop_index_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_name([NotNull] PreSQLParser.Table_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.join_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoin_constraint([NotNull] PreSQLParser.Join_constraintContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.cte_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCte_table_name([NotNull] PreSQLParser.Cte_table_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.indexed_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexed_column([NotNull] PreSQLParser.Indexed_columnContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.literal_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral_value([NotNull] PreSQLParser.Literal_valueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.disconnect_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDisconnect_stmt([NotNull] PreSQLParser.Disconnect_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.transaction_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransaction_name([NotNull] PreSQLParser.Transaction_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.column_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_def([NotNull] PreSQLParser.Column_defContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.sql_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSql_stmt([NotNull] PreSQLParser.Sql_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.new_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNew_table_name([NotNull] PreSQLParser.New_table_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyword([NotNull] PreSQLParser.KeywordContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.error_message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitError_message([NotNull] PreSQLParser.Error_messageContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.create_index_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_index_stmt([NotNull] PreSQLParser.Create_index_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_operator([NotNull] PreSQLParser.Unary_operatorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.rollback_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRollback_stmt([NotNull] PreSQLParser.Rollback_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.join_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoin_operator([NotNull] PreSQLParser.Join_operatorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.collation_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollation_name([NotNull] PreSQLParser.Collation_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.update_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdate_stmt([NotNull] PreSQLParser.Update_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.column_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_alias([NotNull] PreSQLParser.Column_aliasContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.alter_table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table_stmt([NotNull] PreSQLParser.Alter_table_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] PreSQLParser.NameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.table_or_index_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_or_index_name([NotNull] PreSQLParser.Table_or_index_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.module_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule_name([NotNull] PreSQLParser.Module_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.table_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_alias([NotNull] PreSQLParser.Table_aliasContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.drop_trigger_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_trigger_stmt([NotNull] PreSQLParser.Drop_trigger_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.module_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule_argument([NotNull] PreSQLParser.Module_argumentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.create_trigger_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_trigger_stmt([NotNull] PreSQLParser.Create_trigger_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.signed_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSigned_number([NotNull] PreSQLParser.Signed_numberContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.ordering_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrdering_term([NotNull] PreSQLParser.Ordering_termContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.table_or_subquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_or_subquery([NotNull] PreSQLParser.Table_or_subqueryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.error"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitError([NotNull] PreSQLParser.ErrorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.commit_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommit_stmt([NotNull] PreSQLParser.Commit_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.select_or_values"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_or_values([NotNull] PreSQLParser.Select_or_valuesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.select_core"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_core([NotNull] PreSQLParser.Select_coreContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.savepoint_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSavepoint_name([NotNull] PreSQLParser.Savepoint_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.conflict_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConflict_clause([NotNull] PreSQLParser.Conflict_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.trigger_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrigger_name([NotNull] PreSQLParser.Trigger_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.foreign_key_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeign_key_clause([NotNull] PreSQLParser.Foreign_key_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.any_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAny_name([NotNull] PreSQLParser.Any_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.insert_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsert_stmt([NotNull] PreSQLParser.Insert_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.common_table_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommon_table_expression([NotNull] PreSQLParser.Common_table_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.drop_table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_table_stmt([NotNull] PreSQLParser.Drop_table_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] PreSQLParser.ExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.create_table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_table_stmt([NotNull] PreSQLParser.Create_table_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.drop_view_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_view_stmt([NotNull] PreSQLParser.Drop_view_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.index_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_name([NotNull] PreSQLParser.Index_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.view_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitView_name([NotNull] PreSQLParser.View_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.with_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWith_clause([NotNull] PreSQLParser.With_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.qualified_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualified_table_name([NotNull] PreSQLParser.Qualified_table_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.create_view_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_view_stmt([NotNull] PreSQLParser.Create_view_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.column_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_constraint([NotNull] PreSQLParser.Column_constraintContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.database_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatabase_name([NotNull] PreSQLParser.Database_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.connect_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConnect_stmt([NotNull] PreSQLParser.Connect_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_name([NotNull] PreSQLParser.Column_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.result_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResult_column([NotNull] PreSQLParser.Result_columnContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParse([NotNull] PreSQLParser.ParseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.table_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_constraint([NotNull] PreSQLParser.Table_constraintContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.pragma_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPragma_name([NotNull] PreSQLParser.Pragma_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.foreign_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeign_table([NotNull] PreSQLParser.Foreign_tableContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_name([NotNull] PreSQLParser.Function_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.join_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoin_clause([NotNull] PreSQLParser.Join_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.raise_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaise_function([NotNull] PreSQLParser.Raise_functionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.select_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_stmt([NotNull] PreSQLParser.Select_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PreSQLParser.delete_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelete_stmt([NotNull] PreSQLParser.Delete_stmtContext context);
}
} // namespace WindowsFormsApplication2
